$file = 'c:\Users\TABITHA\Desktop\VISION SCREEN\VisionScreen-Mobile-Application\lib\screens\home_screen.dart'
$lines = [System.IO.File]::ReadAllLines($file)

$newContent = @(
'                   children: [',
'                    // ── Brand row ──',
'                    Row(',
'                      mainAxisAlignment: MainAxisAlignment.spaceBetween,',
'                      children: [',
'                        // Logo left',
'                        Row(children: [',
'                          Container(',
'                            width: 28, height: 28,',
'                            decoration: BoxDecoration(',
'                              color: Colors.white.withValues(alpha: 0.2),',
'                              borderRadius: BorderRadius.circular(8),',
'                              border: Border.all(color: Colors.white.withValues(alpha: 0.4)),',
'                            ),',
'                            child: Center(',
'                              child: CustomPaint(',
'                                size: const Size(16, 16),',
'                                painter: AuthEyePainter(color: Colors.white),',
'                              ),',
'                            ),',
'                          ),',
'                          const SizedBox(width: 8),',
'                          RichText(',
'                            text: TextSpan(',
'                              style: GoogleFonts.nunito(fontSize: 18, fontWeight: FontWeight.w900),',
'                              children: const [',
'                                TextSpan(text: ''Vision'', style: TextStyle(color: Colors.white)),',
'                                TextSpan(text: ''Screen'', style: TextStyle(color: Colors.black)),',
'                              ],',
'                            ),',
'                          ),',
'                        ]),',
'                        // Profile avatar right',
'                        Container(',
'                          width: 38, height: 38,',
'                          decoration: BoxDecoration(',
'                            borderRadius: BorderRadius.circular(12),',
'                            gradient: const LinearGradient(',
'                              colors: [AppColors.greenDark, AppColors.green],',
'                              begin: Alignment.topLeft, end: Alignment.bottomRight,',
'                            ),',
'                            border: Border.all(color: Colors.white, width: 2),',
'                          ),',
'                          child: ClipRRect(',
'                            borderRadius: BorderRadius.circular(10),',
'                            child: _chwPhoto.isNotEmpty && File(_chwPhoto).existsSync()',
'                                ? Image.file(File(_chwPhoto), width: 38, height: 38, fit: BoxFit.cover)',
'                                : Center(',
'                                    child: Text(',
'                                      _chwName.trim().isEmpty ? ''VS'' : _chwName.trim().split('' '').map((w) => w.isEmpty ? '''' : w[0]).take(2).join().toUpperCase(),',
'                                      style: GoogleFonts.nunito(color: Colors.white, fontWeight: FontWeight.w900, fontSize: 13),',
'                                    ),',
'                                  ),',
'                          ),',
'                        ),',
'                      ],',
'                    ),',
'                    const SizedBox(height: 12),',
'                    // ── Greeting ──',
'                    RichText(',
'                      text: TextSpan(',
'                        style: GoogleFonts.nunito(fontSize: 22, fontWeight: FontWeight.w900),',
'                        children: [',
'                          TextSpan(',
'                            text: _now.hour < 12 ? ''Good morning, '' : _now.hour < 17 ? ''Good afternoon, '' : ''Good evening, '',',
'                            style: const TextStyle(color: Colors.white, fontSize: 22),',
'                          ),',
'                          TextSpan(',
'                            text: (_chwName.isNotEmpty ? _chwName.split('' '').first : ''CHW'') + ''!'',',
'                            style: const TextStyle(color: Color(0xFFFFD700), fontSize: 22, fontStyle: FontStyle.italic),',
'                          ),',
'                        ],',
'                      ),',
'                    ),',
'                    const SizedBox(height: 6),',
'                    // ── Location + time row ──',
'                    Row(',
'                      children: [',
'                        GestureDetector(',
'                          onTap: _fetchLocation,',
'                          child: Row(children: [',
'                            Icon(',
'                              _locationLabel.contains(''retry'') || _locationLabel.contains(''timeout'')',
'                                  ? Icons.refresh_rounded : Icons.location_on_rounded,',
'                              size: 12, color: Colors.white,',
'                            ),',
'                            const SizedBox(width: 4),',
'                            ConstrainedBox(',
'                              constraints: const BoxConstraints(maxWidth: 160),',
'                              child: Text(_locationLabel, overflow: TextOverflow.ellipsis,',
'                                style: GoogleFonts.poppins(fontSize: 11,',
'                                  color: Colors.white, fontWeight: FontWeight.w600)),',
'                            ),',
'                          ]),',
'                        ),',
'                        const Spacer(),',
'                        Container(',
'                          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),',
'                          decoration: BoxDecoration(',
'                            color: Colors.white.withValues(alpha: 0.2),',
'                            borderRadius: BorderRadius.circular(99),',
'                            border: Border.all(color: Colors.white.withValues(alpha: 0.3)),',
'                          ),',
'                          child: Row(children: [',
'                            Icon(Icons.access_time_rounded, size: 11, color: Colors.white),',
'                            const SizedBox(width: 4),',
'                            Text(_formatTime(_now), style: GoogleFonts.poppins(',
'                                fontSize: 11, fontWeight: FontWeight.w800, color: Colors.white)),',
'                          ]),',
'                        ),',
'                      ],',
'                    ),',
'                    const SizedBox(height: 4),',
'                    // ── Date row ──',
'                    Row(children: [',
'                      Icon(Icons.calendar_today_rounded, size: 11, color: Colors.white),',
'                      const SizedBox(width: 4),',
'                      Text(_formatDate(_now), style: GoogleFonts.poppins(',
'                          fontSize: 11, color: Colors.white, fontWeight: FontWeight.w600)),',
'                    ]),',
'                    const SizedBox(height: 14),',
'                    // ── Sync bar ──',
'                    _buildSyncBar(),',
'                    const SizedBox(height: 12),',
'                    // ── Stats ──',
'                    _buildStatsRow(),',
'                  ],'
)

# Find line 461 (children: [) and line 567 (],) to replace
$lines = $lines[0..461] + $newContent + $lines[567..($lines.Length-1)]
[System.IO.File]::WriteAllLines($file, $lines)
Write-Host "Done"
