$file = 'c:\Users\TABITHA\Desktop\VISION SCREEN\VisionScreen-Mobile-Application\lib\screens\home_screen.dart'
$lines = [System.IO.File]::ReadAllLines($file)

$newCard = @(
'  Widget _buildActionCard(Map a) {',
'    final accent = (a[''overlayColors''] as List<Color>).first;',
'    return Material(',
'      color: Colors.white,',
'      borderRadius: BorderRadius.circular(16),',
'      child: InkWell(',
'        borderRadius: BorderRadius.circular(16),',
'        onTap: () {',
'          if (a[''title''] == ''New Screening'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const NewScreeningScreen(startWithNewPatient: true)),',
'            ).then((_) => _loadDbStats());',
'          } else if (a[''title''] == ''Bulk Mode'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const BulkModeScreen()),',
'            ).then((_) => _loadDbStats());',
'          } else if (a[''title''] == ''Training'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const TrainingScreen()));',
'          } else if (a[''title''] == ''Analytics'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const AnalyticsScreen()));',
'          }',
'        },',
'        splashColor: AppColors.greenHero,',
'        highlightColor: AppColors.greenHero,',
'        child: Container(',
'          decoration: BoxDecoration(',
'            borderRadius: BorderRadius.circular(16),',
'            border: Border.all(color: AppColors.borderColor, width: 1.5),',
'            boxShadow: [',
'              BoxShadow(',
'                color: AppColors.cardShadow,',
'                blurRadius: 8,',
'                offset: const Offset(0, 3),',
'              ),',
'            ],',
'          ),',
'          child: ClipRRect(',
'            borderRadius: BorderRadius.circular(15),',
'            child: Column(',
'              crossAxisAlignment: CrossAxisAlignment.start,',
'              children: [',
'                // Image top half',
'                Expanded(',
'                  child: Builder(builder: (_) {',
'                    final img = a[''image''] as String;',
'                    if (img.startsWith(''asset:'')) {',
'                      return Image.asset(',
'                        img.substring(6),',
'                        fit: BoxFit.cover,',
'                        width: double.infinity,',
'                        errorBuilder: (_, __, ___) => Container(color: AppColors.greenHero),',
'                      );',
'                    }',
'                    return Image.network(',
'                      img, fit: BoxFit.cover, width: double.infinity,',
'                      errorBuilder: (_, __, ___) => Container(color: AppColors.greenHero),',
'                    );',
'                  }),',
'                ),',
'                // White bottom info strip',
'                Padding(',
'                  padding: const EdgeInsets.fromLTRB(10, 8, 10, 8),',
'                  child: Row(',
'                    children: [',
'                      Container(',
'                        width: 28, height: 28,',
'                        decoration: BoxDecoration(',
'                          color: AppColors.greenHero,',
'                          borderRadius: BorderRadius.circular(8),',
'                          border: Border.all(color: AppColors.borderColor),',
'                        ),',
'                        child: Icon(a[''icon''] as IconData,',
'                            color: AppColors.greenDark, size: 14),',
'                      ),',
'                      const SizedBox(width: 8),',
'                      Expanded(',
'                        child: Column(',
'                          crossAxisAlignment: CrossAxisAlignment.start,',
'                          mainAxisSize: MainAxisSize.min,',
'                          children: [',
'                            Text(a[''title''] as String,',
'                                style: GoogleFonts.nunito(',
'                                    fontSize: 12,',
'                                    fontWeight: FontWeight.w800,',
'                                    color: AppColors.textDark)),',
'                            Text(a[''sub''] as String,',
'                                style: GoogleFonts.poppins(',
'                                    fontSize: 9,',
'                                    color: AppColors.textMuted)),',
'                          ],',
'                        ),',
'                      ),',
'                      Container(',
'                        padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),',
'                        decoration: BoxDecoration(',
'                          color: AppColors.greenHero,',
'                          borderRadius: BorderRadius.circular(99),',
'                          border: Border.all(color: AppColors.borderColor),',
'                        ),',
'                        child: Text(a[''tag''] as String,',
'                            style: GoogleFonts.poppins(',
'                                fontSize: 7,',
'                                fontWeight: FontWeight.w700,',
'                                color: AppColors.greenDark,',
'                                letterSpacing: 0.8)),',
'                      ),',
'                    ],',
'                  ),',
'                ),',
'              ],',
'            ),',
'          ),',
'        ),',
'      ),',
'    );',
'  }'
)

$lines = $lines[0..1101] + $newCard + $lines[1273..($lines.Length-1)]
[System.IO.File]::WriteAllLines($file, $lines)
Write-Host "Done"
