$file = 'c:\Users\TABITHA\Desktop\VISION SCREEN\VisionScreen-Mobile-Application\lib\screens\home_screen.dart'
$lines = [System.IO.File]::ReadAllLines($file)

$newStats = @(
'  Widget _buildStatsRow() {',
'    return Row(',
'      children: [',
'        _buildStatCard(',
"          number: '\$_totalScreened',",
"          label: 'Screened',",
"          icon: Icons.remove_red_eye_outlined,",
'          cardColor: AppColors.green,',
'          iconBg: const Color(0xFF27AE60),',
'        ),',
'        const SizedBox(width: 8),',
'        _buildStatCard(',
"          number: '\$_totalReferred',",
"          label: 'Referred',",
"          icon: Icons.warning_amber_rounded,",
'          cardColor: const Color(0xFFF59E0B),',
'          iconBg: const Color(0xFFD97706),',
'        ),',
'        const SizedBox(width: 8),',
'        _buildStatCard(',
"          number: '\$_unsyncedCount',",
"          label: 'Unsynced',",
"          icon: Icons.sync_rounded,",
'          cardColor: const Color(0xFFEF4444),',
'          iconBg: const Color(0xFFDC2626),',
'        ),',
'      ],',
'    );',
'  }',
'',
'  Widget _buildStatCard({',
'    required String number,',
'    required String label,',
'    required IconData icon,',
'    required Color cardColor,',
'    required Color iconBg,',
'  }) {',
'    return Expanded(',
'      child: Container(',
'        padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 8),',
'        decoration: BoxDecoration(',
'          color: cardColor,',
'          borderRadius: BorderRadius.circular(16),',
'          boxShadow: [',
'            BoxShadow(',
'              color: cardColor.withValues(alpha: 0.45),',
'              blurRadius: 12,',
'              offset: const Offset(0, 4),',
'            ),',
'          ],',
'        ),',
'        child: Column(',
'          mainAxisSize: MainAxisSize.min,',
'          children: [',
'            Container(',
'              width: 32, height: 32,',
'              decoration: BoxDecoration(',
'                color: iconBg,',
'                borderRadius: BorderRadius.circular(10),',
'              ),',
'              child: Icon(icon, size: 16, color: Colors.white),',
'            ),',
'            const SizedBox(height: 6),',
'            Text(number,',
'                style: GoogleFonts.nunito(',
'                    fontSize: 22,',
'                    fontWeight: FontWeight.w900,',
'                    color: Colors.white,',
'                    height: 1.0)),',
'            const SizedBox(height: 2),',
'            Text(label,',
'                style: GoogleFonts.poppins(',
'                    fontSize: 9,',
'                    color: Colors.white.withValues(alpha: 0.9),',
'                    fontWeight: FontWeight.w600,',
'                    letterSpacing: 0.3)),',
'          ],',
'        ),',
'      ),',
'    );',
'  }'
)

$lines = $lines[0..830] + $newStats + $lines[872..($lines.Length-1)]
[System.IO.File]::WriteAllLines($file, $lines)
Write-Host "Done"
