$file = 'c:\Users\TABITHA\Desktop\VISION SCREEN\VisionScreen-Mobile-Application\lib\screens\home_screen.dart'
$lines = [System.IO.File]::ReadAllLines($file)

$newHeader = @(
'  Widget _buildHeader() {',
'    return ClipPath(',
'      clipper: _HomeWaveClipper(),',
'      child: Container(',
'        width: double.infinity,',
'        decoration: const BoxDecoration(',
'          gradient: LinearGradient(',
'            colors: [AppColors.greenDark, AppColors.green],',
'            begin: Alignment.topLeft,',
'            end: Alignment.bottomRight,',
'          ),',
'        ),',
'        child: SafeArea(',
'          bottom: false,',
'          child: Stack(',
'            children: [',
'              Positioned.fill(child: CustomPaint(painter: _HomeDotPainter())),',
'              Padding(',
'                padding: const EdgeInsets.fromLTRB(18, 14, 18, 52),',
'                child: Column(',
'                  crossAxisAlignment: CrossAxisAlignment.start,',
'                  children: [',
'                    _buildUserRow(),',
'                    const SizedBox(height: 14),',
'                    RichText(',
'                      text: TextSpan(',
'                        style: GoogleFonts.nunito(fontSize: 22, fontWeight: FontWeight.w900),',
'                        children: [',
"                          const TextSpan(text: 'Ready to screen, ', style: TextStyle(color: Colors.white)),",
'                          TextSpan(',
"                            text: _chwName.isNotEmpty ? _chwName.split(' ').first : 'CHW',",
'                            style: const TextStyle(color: Colors.black),',
'                          ),',
"                          const TextSpan(text: '!', style: TextStyle(color: Colors.white)),",
'                        ],',
'                      ),',
'                    ),',
'                    const SizedBox(height: 6),',
'                    Row(',
'                      children: [',
'                        GestureDetector(',
'                          onTap: _fetchLocation,',
'                          child: Row(',
'                            children: [',
'                              Icon(',
"                                _locationLabel.contains('retry') || _locationLabel.contains('timeout')",
'                                    ? Icons.refresh_rounded : Icons.location_on_rounded,',
'                                size: 11, color: Colors.white.withValues(alpha: 0.85),',
'                              ),',
'                              const SizedBox(width: 4),',
'                              ConstrainedBox(',
'                                constraints: const BoxConstraints(maxWidth: 160),',
'                                child: Text(_locationLabel, overflow: TextOverflow.ellipsis,',
'                                  style: GoogleFonts.poppins(fontSize: 11,',
'                                    color: Colors.white.withValues(alpha: 0.85), fontWeight: FontWeight.w500)),',
'                              ),',
'                            ],',
'                          ),',
'                        ),',
'                        const Spacer(),',
'                        Container(',
'                          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),',
'                          decoration: BoxDecoration(',
'                            color: Colors.white.withValues(alpha: 0.2),',
'                            borderRadius: BorderRadius.circular(99),',
'                            border: Border.all(color: Colors.white.withValues(alpha: 0.3)),',
'                          ),',
'                          child: Row(children: [',
'                            Icon(Icons.access_time_rounded, size: 10, color: Colors.white),',
'                            const SizedBox(width: 4),',
'                            Text(_formatTime(_now), style: GoogleFonts.poppins(',
'                                fontSize: 11, fontWeight: FontWeight.w700, color: Colors.white)),',
'                          ]),',
'                        ),',
'                      ],',
'                    ),',
'                    const SizedBox(height: 4),',
'                    Row(children: [',
'                      Icon(Icons.calendar_today_rounded, size: 11, color: Colors.white.withValues(alpha: 0.85)),',
'                      const SizedBox(width: 4),',
'                      Text(_formatDate(_now), style: GoogleFonts.poppins(',
'                          fontSize: 11, color: Colors.white.withValues(alpha: 0.85), fontWeight: FontWeight.w500)),',
'                    ]),',
'                    const SizedBox(height: 14),',
'                    _buildSyncBar(),',
'                    const SizedBox(height: 12),',
'                    _buildStatsRow(),',
'                  ],',
'                ),',
'              ),',
'            ],',
'          ),',
'        ),',
'      ),',
'    );',
'  }'
)

$lines = $lines[0..437] + $newHeader + $lines[547..($lines.Length-1)]
[System.IO.File]::WriteAllLines($file, $lines)
Write-Host "Done"
