$file = 'c:\Users\TABITHA\Desktop\VISION SCREEN\VisionScreen-Mobile-Application\lib\screens\home_screen.dart'
$lines = [System.IO.File]::ReadAllLines($file)

$newSync = @(
'  Widget _buildSyncBar() {',
'    return GestureDetector(',
'      onTap: _isSyncing ? null : _doSync,',
'      child: Container(',
'        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 9),',
'        decoration: BoxDecoration(',
'          color: Colors.white.withValues(alpha: 0.18),',
'          borderRadius: BorderRadius.circular(12),',
'          border: Border.all(color: Colors.white.withValues(alpha: 0.35)),',
'        ),',
'        child: Row(',
'          children: [',
'            AnimatedBuilder(',
'              animation: _pulseAnimation,',
'              builder: (context, child) => Opacity(',
'                opacity: _isSyncing ? 1.0 : _pulseAnimation.value,',
'                child: Container(',
'                  width: 7, height: 7,',
'                  decoration: BoxDecoration(',
'                    color: _isSyncing ? const Color(0xFF22C55E) : Colors.white,',
'                    shape: BoxShape.circle,',
'                  ),',
'                ),',
'              ),',
'            ),',
'            const SizedBox(width: 8),',
'            Expanded(',
'              child: Text(',
"                _isSyncing ? 'Syncing...' : '\$_unsyncedCount record\${_unsyncedCount == 1 ? '' : 's'} pending sync',",
'                style: GoogleFonts.poppins(',
'                    fontSize: 11,',
'                    color: Colors.white.withValues(alpha: 0.9),',
'                    fontWeight: FontWeight.w500),',
'              ),',
'            ),',
'            _isSyncing',
'                ? const SizedBox(',
'                    width: 12, height: 12,',
'                    child: CircularProgressIndicator(',
'                      strokeWidth: 1.5, color: Colors.white,',
'                    ),',
'                  )',
"                : Text('Sync Now',",
'                    style: GoogleFonts.poppins(',
'                        fontSize: 10,',
'                        color: Colors.white,',
'                        fontWeight: FontWeight.w700)),',
'          ],',
'        ),',
'      ),',
'    );',
'  }'
)

$lines = $lines[0..776] + $newSync + $lines[849..($lines.Length-1)]
[System.IO.File]::WriteAllLines($file, $lines)
Write-Host "Done"
