$file = 'c:\Users\TABITHA\Desktop\VISION SCREEN\VisionScreen-Mobile-Application\lib\screens\home_screen.dart'
$lines = [System.IO.File]::ReadAllLines($file)

$newCard = @(
'  Widget _buildActionCard(Map a) {',
'    final accent = (a[''overlayColors''] as List<Color>).first;',
'    final img = a[''image''] as String;',
'    return Material(',
'      color: Colors.transparent,',
'      borderRadius: BorderRadius.circular(18),',
'      child: InkWell(',
'        borderRadius: BorderRadius.circular(18),',
'        onTap: () {',
'          if (a[''title''] == ''New Screening'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const NewScreeningScreen(startWithNewPatient: true)),',
'            ).then((_) => _loadDbStats());',
'          } else if (a[''title''] == ''Bulk Mode'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const BulkModeScreen()),',
'            ).then((_) => _loadDbStats());',
'          } else if (a[''title''] == ''Training'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const TrainingScreen()));',
'          } else if (a[''title''] == ''Analytics'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const AnalyticsScreen()));',
'          }',
'        },',
'        splashColor: accent.withValues(alpha: 0.15),',
'        highlightColor: accent.withValues(alpha: 0.08),',
'        child: Container(',
'          decoration: BoxDecoration(',
'            borderRadius: BorderRadius.circular(18),',
'            border: Border.all(color: accent.withValues(alpha: 0.35), width: 1.5),',
'            boxShadow: [',
'              BoxShadow(',
'                color: accent.withValues(alpha: 0.22),',
'                blurRadius: 16,',
'                offset: const Offset(0, 6),',
'              ),',
'            ],',
'          ),',
'          child: ClipRRect(',
'            borderRadius: BorderRadius.circular(17),',
'            child: Stack(',
'              fit: StackFit.expand,',
'              children: [',
'                // Background image',
'                img.startsWith(''asset:'')',
'                    ? Image.asset(img.substring(6), fit: BoxFit.cover,',
'                        errorBuilder: (_, __, ___) => Container(color: accent.withValues(alpha: 0.15)))',
'                    : Image.network(img, fit: BoxFit.cover,',
'                        errorBuilder: (_, __, ___) => Container(color: accent.withValues(alpha: 0.15))),',
'                // Frosted glass overlay',
'                Container(',
'                  decoration: BoxDecoration(',
'                    gradient: LinearGradient(',
'                      begin: Alignment.topCenter,',
'                      end: Alignment.bottomCenter,',
'                      colors: [',
'                        Colors.white.withValues(alpha: 0.15),',
'                        Colors.white.withValues(alpha: 0.82),',
'                      ],',
'                    ),',
'                  ),',
'                ),',
'                // Colored left stripe',
'                Positioned(',
'                  left: 0, top: 0, bottom: 0,',
'                  child: Container(',
'                    width: 5,',
'                    decoration: BoxDecoration(',
'                      gradient: LinearGradient(',
'                        colors: [accent, (a[''overlayColors''] as List<Color>)[1]],',
'                        begin: Alignment.topCenter,',
'                        end: Alignment.bottomCenter,',
'                      ),',
'                    ),',
'                  ),',
'                ),',
'                // Content',
'                Padding(',
'                  padding: const EdgeInsets.fromLTRB(14, 12, 10, 12),',
'                  child: Column(',
'                    crossAxisAlignment: CrossAxisAlignment.start,',
'                    mainAxisAlignment: MainAxisAlignment.spaceBetween,',
'                    children: [',
'                      Row(',
'                        mainAxisAlignment: MainAxisAlignment.spaceBetween,',
'                        children: [',
'                          Container(',
'                            width: 34, height: 34,',
'                            decoration: BoxDecoration(',
'                              color: accent.withValues(alpha: 0.15),',
'                              borderRadius: BorderRadius.circular(10),',
'                              border: Border.all(color: accent.withValues(alpha: 0.4)),',
'                            ),',
'                            child: Icon(a[''icon''] as IconData, color: accent, size: 17),',
'                          ),',
'                          Container(',
'                            padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 3),',
'                            decoration: BoxDecoration(',
'                              color: accent.withValues(alpha: 0.12),',
'                              borderRadius: BorderRadius.circular(99),',
'                              border: Border.all(color: accent.withValues(alpha: 0.35)),',
'                            ),',
'                            child: Text(a[''tag''] as String,',
'                              style: GoogleFonts.poppins(fontSize: 7, fontWeight: FontWeight.w800,',
'                                color: accent, letterSpacing: 0.8)),',
'                          ),',
'                        ],',
'                      ),',
'                      Column(',
'                        crossAxisAlignment: CrossAxisAlignment.start,',
'                        children: [',
'                          Text(a[''title''] as String,',
'                            style: GoogleFonts.nunito(fontSize: 13, fontWeight: FontWeight.w900,',
'                              color: AppColors.textDark)),',
'                          Text(a[''sub''] as String,',
'                            style: GoogleFonts.poppins(fontSize: 9,',
'                              color: AppColors.textMuted, fontWeight: FontWeight.w500)),',
'                        ],',
'                      ),',
'                    ],',
'                  ),',
'                ),',
'              ],',
'            ),',
'          ),',
'        ),',
'      ),',
'    );',
'  }'
)

$lines = $lines[0..1299] + $newCard + $lines[1410..($lines.Length-1)]
[System.IO.File]::WriteAllLines($file, $lines)
Write-Host "Done"
