$file = 'c:\Users\TABITHA\Desktop\VISION SCREEN\VisionScreen-Mobile-Application\lib\screens\home_screen.dart'
$lines = [System.IO.File]::ReadAllLines($file)

# Also update overlayColors to vibrant accent colors
$lines[1258] = "        'overlayColors': [const Color(0xFF2ECC71), const Color(0xFF27AE60)],"
$lines[1266] = "        'overlayColors': [const Color(0xFF3B82F6), const Color(0xFF1D4ED8)],"
$lines[1274] = "        'overlayColors': [const Color(0xFFF59E0B), const Color(0xFFD97706)],"
$lines[1283] = "        'overlayColors': [const Color(0xFF8B5CF6), const Color(0xFF6D28D9)],"

$newCard = @(
'  Widget _buildActionCard(Map a) {',
'    final accent = (a[''overlayColors''] as List<Color>).first;',
'    return Material(',
'      color: Colors.transparent,',
'      borderRadius: BorderRadius.circular(18),',
'      child: InkWell(',
'        borderRadius: BorderRadius.circular(18),',
'        onTap: () {',
'          if (a[''title''] == ''New Screening'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const NewScreeningScreen(startWithNewPatient: true)),',
'            ).then((_) => _loadDbStats());',
'          } else if (a[''title''] == ''Bulk Mode'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const BulkModeScreen()),',
'            ).then((_) => _loadDbStats());',
'          } else if (a[''title''] == ''Training'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const TrainingScreen()));',
'          } else if (a[''title''] == ''Analytics'') {',
'            Navigator.push(context,',
'              MaterialPageRoute(builder: (_) => const AnalyticsScreen()));',
'          }',
'        },',
'        splashColor: accent.withValues(alpha: 0.1),',
'        highlightColor: accent.withValues(alpha: 0.05),',
'        child: Container(',
'          decoration: BoxDecoration(',
'            color: Colors.white.withValues(alpha: 0.92),',
'            borderRadius: BorderRadius.circular(18),',
'            border: Border.all(color: accent.withValues(alpha: 0.25), width: 1.5),',
'            boxShadow: [',
'              BoxShadow(',
'                color: accent.withValues(alpha: 0.18),',
'                blurRadius: 16,',
'                offset: const Offset(0, 6),',
'              ),',
'              BoxShadow(',
'                color: Colors.white.withValues(alpha: 0.8),',
'                blurRadius: 4,',
'                offset: const Offset(0, -2),',
'              ),',
'            ],',
'          ),',
'          child: ClipRRect(',
'            borderRadius: BorderRadius.circular(17),',
'            child: Row(',
'              children: [',
'                // Colored left border stripe',
'                Container(',
'                  width: 5,',
'                  decoration: BoxDecoration(',
'                    gradient: LinearGradient(',
'                      colors: [accent, (a[''overlayColors''] as List<Color>)[1]],',
'                      begin: Alignment.topCenter,',
'                      end: Alignment.bottomCenter,',
'                    ),',
'                  ),',
'                ),',
'                // Content',
'                Expanded(',
'                  child: Padding(',
'                    padding: const EdgeInsets.fromLTRB(12, 12, 10, 12),',
'                    child: Column(',
'                      crossAxisAlignment: CrossAxisAlignment.start,',
'                      mainAxisAlignment: MainAxisAlignment.spaceBetween,',
'                      children: [',
'                        // Icon + tag row',
'                        Row(',
'                          mainAxisAlignment: MainAxisAlignment.spaceBetween,',
'                          children: [',
'                            Container(',
'                              width: 36, height: 36,',
'                              decoration: BoxDecoration(',
'                                color: accent.withValues(alpha: 0.12),',
'                                borderRadius: BorderRadius.circular(10),',
'                                border: Border.all(color: accent.withValues(alpha: 0.3)),',
'                              ),',
'                              child: Icon(a[''icon''] as IconData, color: accent, size: 18),',
'                            ),',
'                            Container(',
'                              padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 3),',
'                              decoration: BoxDecoration(',
'                                color: accent.withValues(alpha: 0.1),',
'                                borderRadius: BorderRadius.circular(99),',
'                                border: Border.all(color: accent.withValues(alpha: 0.3)),',
'                              ),',
'                              child: Text(a[''tag''] as String,',
'                                style: GoogleFonts.poppins(fontSize: 7, fontWeight: FontWeight.w800,',
'                                  color: accent, letterSpacing: 0.8)),',
'                            ),',
'                          ],',
'                        ),',
'                        const SizedBox(height: 8),',
'                        // Title + subtitle',
'                        Text(a[''title''] as String,',
'                          style: GoogleFonts.nunito(fontSize: 13, fontWeight: FontWeight.w900,',
'                            color: AppColors.textDark)),',
'                        Text(a[''sub''] as String,',
'                          style: GoogleFonts.poppins(fontSize: 9, color: AppColors.textMuted)),',
'                      ],',
'                    ),',
'                  ),',
'                ),',
'              ],',
'            ),',
'          ),',
'        ),',
'      ),',
'    );',
'  }'
)

$lines = $lines[0..1299] + $newCard + $lines[1417..($lines.Length-1)]
[System.IO.File]::WriteAllLines($file, $lines)
Write-Host "Done"
