$file = 'c:\Users\TABITHA\Desktop\VISION SCREEN\VisionScreen-Mobile-Application\lib\screens\home_screen.dart'
$lines = [System.IO.File]::ReadAllLines($file)

$rightSide = @(
'                        // Online + bell + profile',
'                        Row(children: [',
'                          // Online indicator',
'                          AnimatedContainer(',
'                            duration: const Duration(milliseconds: 300),',
'                            padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 3),',
'                            decoration: BoxDecoration(',
'                              color: _isOffline ? Colors.red.withValues(alpha: 0.25) : Colors.white.withValues(alpha: 0.2),',
'                              borderRadius: BorderRadius.circular(99),',
'                              border: Border.all(color: _isOffline ? Colors.red.withValues(alpha: 0.6) : Colors.white.withValues(alpha: 0.5)),',
'                            ),',
'                            child: Row(mainAxisSize: MainAxisSize.min, children: [',
'                              AnimatedBuilder(',
'                                animation: _pulseAnimation,',
'                                builder: (_, __) => Opacity(',
'                                  opacity: _isOffline ? 1.0 : _pulseAnimation.value,',
'                                  child: Container(',
'                                    width: 6, height: 6,',
'                                    decoration: BoxDecoration(',
'                                      color: _isOffline ? Colors.red : Colors.white,',
'                                      shape: BoxShape.circle,',
'                                    ),',
'                                  ),',
'                                ),',
'                              ),',
'                              const SizedBox(width: 4),',
'                              Text(_isOffline ? ''Offline'' : ''Online'',',
'                                style: GoogleFonts.poppins(fontSize: 9, fontWeight: FontWeight.w700,',
'                                  color: _isOffline ? Colors.red : Colors.white)),',
'                            ]),',
'                          ),',
'                          const SizedBox(width: 8),',
'                          // Notification bell',
'                          GestureDetector(',
'                            onTap: () async {',
'                              await Navigator.push(context, PageRouteBuilder(',
'                                pageBuilder: (_, __, ___) => const NotificationsScreen(),',
'                                transitionsBuilder: (_, anim, __, child) => FadeTransition(opacity: anim, child: child),',
'                                transitionDuration: const Duration(milliseconds: 300),',
'                              ));',
'                              if (mounted) setState(() => _notificationCount = 0);',
'                            },',
'                            child: Stack(clipBehavior: Clip.none, children: [',
'                              Container(',
'                                width: 36, height: 36,',
'                                decoration: BoxDecoration(',
'                                  color: Colors.white.withValues(alpha: 0.2),',
'                                  borderRadius: BorderRadius.circular(10),',
'                                  border: Border.all(color: Colors.white.withValues(alpha: 0.4)),',
'                                ),',
'                                child: Icon(',
'                                  _notificationCount > 0 ? Icons.notifications_active_rounded : Icons.notifications_rounded,',
'                                  color: Colors.white, size: 18,',
'                                ),',
'                              ),',
'                              if (_notificationCount > 0)',
'                                Positioned(',
'                                  top: -4, right: -4,',
'                                  child: Container(',
'                                    padding: const EdgeInsets.all(4),',
'                                    decoration: const BoxDecoration(',
'                                      color: Color(0xFFEF4444),',
'                                      shape: BoxShape.circle,',
'                                    ),',
'                                    child: Text(''$_notificationCount'',',
'                                      style: GoogleFonts.poppins(fontSize: 8, fontWeight: FontWeight.w800, color: Colors.white)),',
'                                  ),',
'                                ),',
'                            ]),',
'                          ),',
'                          const SizedBox(width: 8),',
'                          // Profile avatar',
'                          Container(',
'                            width: 38, height: 38,',
'                            decoration: BoxDecoration(',
'                              borderRadius: BorderRadius.circular(12),',
'                              gradient: const LinearGradient(',
'                                colors: [AppColors.greenDark, AppColors.green],',
'                                begin: Alignment.topLeft, end: Alignment.bottomRight,',
'                              ),',
'                              border: Border.all(color: Colors.white, width: 2),',
'                            ),',
'                            child: ClipRRect(',
'                              borderRadius: BorderRadius.circular(10),',
'                              child: _chwPhoto.isNotEmpty && File(_chwPhoto).existsSync()',
'                                  ? Image.file(File(_chwPhoto), width: 38, height: 38, fit: BoxFit.cover)',
'                                  : Center(',
'                                      child: Text(',
'                                        _chwName.trim().isEmpty ? ''VS'' : _chwName.trim().split('' '').map((w) => w.isEmpty ? '''' : w[0]).take(2).join().toUpperCase(),',
'                                        style: GoogleFonts.nunito(color: Colors.white, fontWeight: FontWeight.w900, fontSize: 13),',
'                                      ),',
'                                    ),',
'                            ),',
'                          ),',
'                        ]),'
)

$lines = $lines[0..493] + $rightSide + $lines[517..($lines.Length-1)]
[System.IO.File]::WriteAllLines($file, $lines)
Write-Host "Done"
