import 'package:flutter/material.dart';

const patientMissingVaValue = 'Not tested';

class PatientListItem {
  const PatientListItem({
    required this.initials,
    required this.avatarGradient,
    required this.photoUrl,
    required this.name,
    required this.age,
    required this.gender,
    required this.village,
    required this.ageGroup,
    required this.od,
    required this.os,
    required this.ou,
    required this.outcome,
    required this.date,
    required this.id,
    required this.phone,
    this.facility,
    this.referralStatus,
    this.campaignId,
    List<String>? conditions,
  }) : conditions = conditions ?? const <String>[];

  final String initials;
  final List<Color> avatarGradient;
  final String photoUrl;
  final String name;
  final int age;
  final String gender;
  final String village;
  final String ageGroup;
  final String od;
  final String os;
  final String ou;
  final String outcome;
  final String date;
  final String id;
  final String phone;
  final String? facility;
  final String? referralStatus;
  final String? campaignId;
  final List<String> conditions;

  List<String> get safeConditions => conditions.toList();

  String get demographics => '$age yrs | $gender | $village';

  String get whatsappMessage {
    final status = referralStatus?.toUpperCase() ?? outcome.toUpperCase();
    final subject = outcome == 'refer' ? 'Referral' : 'Patient';
    return '''
*VisionScreen $subject Update*

*Patient:* $name
*Demographics:* $demographics
*Facility:* ${facility ?? 'N/A'}
*Status:* $status

*Visual Acuity*
- OD (Right Eye): $od
- OS (Left Eye): $os
- OU (Both Eyes): $ou

Generated by VisionScreen
''';
  }
}

String normaliseVisualAcuity(String? value) {
  final trimmed = value?.trim() ?? '';
  if (trimmed.isEmpty || trimmed == '�') {
    return patientMissingVaValue;
  }
  return trimmed;
}

String normaliseWhatsAppPhone(String raw) {
  final digits = raw.replaceAll(RegExp(r'[^0-9]'), '');
  if (digits.startsWith('256') && digits.length >= 12) {
    return digits;
  }
  if (digits.startsWith('0') && digits.length == 10) {
    return '256${digits.substring(1)}';
  }
  return digits;
}
